### ISSUE TITLE
Spinning icons

### ISSUE THREAD

**Issue by mistermow** [driftyco/ionicons#210]
In previous version icons like ion-looping were spinning icons. Now they are replaced with ion-loop. How am I able to animate them or do I need to add CSS?

**Comment by felquis** [comment]
@marcalj's solution works fine 
https://github.com/driftyco/ionicons/issues/111#issuecomment-65788526

**Comment by mistermow** [comment]
@felquis sorry i haven't seen this issue yet. I tried this solution but it's not working for me using Ionic + Phonegap on iOS 8.

**Comment by bensperry** [comment]
Hey guys, spinning font icons were removed for various reasons - mainly because each browser renders and displays fonts differently, and as such, the icons wobble when rotated. We're working on a significantly superior solution, which will go live with the next version of ionic (RC0). Here is a preview: http://ionicframework.com/docs/nightly/api/directive/ionSpinner/
