### ISSUE TITLE
Request: Analytics Icon

### ISSUE THREAD

**Issue by DaveJarvis** [driftyco/ionicons#306]
Would like to see an analytics icon developed.

Something to indicate a report file (PDF), possibly along the lines of:

![analytics](https://cloud.githubusercontent.com/assets/2131950/9702165/c7031372-5406-11e5-810f-d1ce50980ea2.png)

**Comment by Ionitron** [comment]
Greetings @DaveJarvis!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
