### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by VicCebedo** [driftyco/ionicons#307]
#### Problem: ####
When I load my page, I just see squares for all icons and in the console, there's a warning:
```
Failed to decode downloaded font: http://my-server.com/xxx/resources/fonts/ionicons.ttf?v=2.0.1
OTS parsing error: invalid version tag
Failed to decode downloaded font: http://my-server.com/xxx/resources/fonts/ionicons.woff?v=2.0.1
OTS parsing error: invalid version tag
```

#### Other details: ####
In my JSP, I have included the ionicons:
This method is NOT OK (this is the Problem):
`<link href="<c:url value="/resources/css/ionicons.min.css" />"rel="stylesheet" type="text/css" />`

This method is OK (workaround):
`<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/">`

`Google Chrome version: Version 45.0.2454.85 m`

**Comment by Ionitron** [comment]
Greetings @VicCebedo!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by VicCebedo** [comment]
Updated to latest version, problem now ok. Thanks!
