### ISSUE TITLE
Hi, would it be possible to get an icon of a honeycomb or hexagon? Thanks a lot.

### ISSUE THREAD

**Issue by EOBecker** [driftyco/ionicons#311]
Hi, would it be possible to get an icon of a honeycomb or hexagon? Thanks a lot.

**Comment by Ionitron** [comment]
Greetings @EOBecker!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
