### ISSUE TITLE
Request : checkmark lock

### ISSUE THREAD

**Issue by aguadoenzo** [driftyco/ionicons#312]
This icon would be extremely usefull when asking a user to confirm his password

**Comment by Ionitron** [comment]
Greetings @aguadoenzo!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
