### ISSUE TITLE
Request: Wallet Icon

### ISSUE THREAD

**Issue by ituhin** [driftyco/ionicons#313]
there is a cash icon, but no wallet icon. i think it will be very useful, as online wallet its pretty common these days

**Comment by Ionitron** [comment]
Greetings @ituhin!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by gauravshegokar** [comment]
There is no wallet icon available. I think it will be very useful for developing wallet application.

**Comment by bensperry** [comment]
We might consider adding this in the future, but right now we're tying to keep the pack small, since file size is becoming an issue for phones.

**Comment by ituhin** [comment]
ohh... just one more icon wont wont be too much :P 
or if we are talking about the file size, then can we have a icon pack builder, like where we can pick the icons we need. i think that will be great.
i am using that cash icon for wallet for now :( 

have a look what I did with ionic - www.dropacoin.im

**Comment by bensperry** [comment]
Nice app! You should submit it to our [showcase](showcase.ionicframework.com)

We are definitely considering building a way to only pull out the icons your apps will need, but we haven't started anything yet - too busy with building Ionic v2 right now!

**Comment by vajohn** [comment]
please please please the wallet or bank or those related are desparate needs. Can't be using the cash for everything

**Comment by rohit29121990** [comment]
can I have wallet icon in ionic 3 icon library
