### ISSUE TITLE
Request: Hardware/Server Icon

### ISSUE THREAD

**Issue by mattalco** [driftyco/ionicons#320]
Would like to have an icon that represents some kind of tower or server hardware.

![computer_hardware_icons-05-512](https://cloud.githubusercontent.com/assets/13972013/10290398/cd28690a-6b71-11e5-90b9-146132f48cfe.png)

**Comment by Ionitron** [comment]
Greetings @mattalco!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
