### ISSUE TITLE
Bug: iOS Calendar Outline Wrong Icon in Font File

### ISSUE THREAD

**Issue by joellebel** [driftyco/ionicons#321]
The ios-calendar-outline font icon does match the "ios-calendar-outline.svg" in the downloadable assets.

Here's what's in the font file when doing a search for "ios calendar" at http://ionicons.com/:

![image](https://cloud.githubusercontent.com/assets/11527994/10349468/832051aa-6cf3-11e5-9896-ab29a8ddf9a4.png)

It's named "ion-ios-calendar-outline"

Here is what is included in the downloadable assets

![image](https://cloud.githubusercontent.com/assets/11527994/10349578/0d765be2-6cf4-11e5-8d01-b9cf91868bfc.png)

...and is named "ios-calendar-outline.svg" I think it either is misnamed or didn't get included for some reason. It would be great if it could be included in the font file. 

PS: To all those working on this project, thanks so much! This is a great tool and has been quite helpful to our development process!

**Comment by Ionitron** [comment]
Greetings @joellebel!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
